config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  #ユーザー用ルーティング
  resources :users, only: [:show, :update, :edit, :destroy]
  # 退会確認ページ用
  get '/users/withdraw' => 'users#withdraw'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  # アバウト,トップページ用
  get '/homes/about' => 'homes#about'
  get '/homes/top' => 'homes#top'
  root to: 'homes#top'

  # 出品ページ用
  get '/items/exhibition' => 'items#exhibition'

  put '/items/finish/:id' => 'items#finish', as: 'item_finish'

  # 商品用ルーティング（コメント、お気に入り）
  put '/items/buy/:id' => 'items#buy', as: 'item_buy'

  put '/items/boost/:id' => 'items#boost', as: 'item_boost'

  resources :items, only: [:index, :show, :create, :edit, :destroy] do
    resource :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    validates :username, presence: true, length: {maximum: 20, minimum: 2}
    attachment :image
    has_many :orders
    has_many :items, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_items, through: :favorites, source: :item, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
		@orders = @user.orders
		@items = @user.items
	end

	def edit
	end

	def update
		#ログインユーザ情報取得
	    user = User.find( current_user.id )
	    #ユーザ情報更新
	    user.update( user_params )
	    flash[:notice] = "ユーザー更新が正常に完了しました。"

	    #Withoutページからユーザが退会状態に変化した場合の処理
	    if user.is_deleted then
		    #logger.debug 'ログアウト処理実行'
		    #ログアウト処理
		    sign_out user
		    flash[:notice] = "退会処理が正常に完了しました。"
		    redirect_to root_path
		else
	    	#（退会していない場合）ログインユーザ詳細画面へ遷移
	    	redirect_to user_path
    end

	end

  	private
	def user_params
    	params.require( :user ).permit( :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted )
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <h3><strong>登録情報編集</strong></h3>
    <%= link_to '退会する', user_withdraw_path, class:"btn btn-danger col-xs-2"%>
    <%= form_for( current_user, url: user_path ) do | f | %>
        <table>
            <tr>
                <th>表示名</th>
                <td>
                    <%= f.text_field :username %>
                </td>
            </tr>
            <tr>
                <th>氏名</th>
                <td>
                    <!--苗字-->
                    <%= f.text_field :last_name %>
                    <!--名前-->
                    <%= f.text_field :first_name %>
                </td>
            </tr>
            <tr>
                <th>カナ</th>
                <td>
                    <!--苗字-->
                    <%= f.text_field :last_name_kana %>
                    <!--名前-->
                    <%= f.text_field :first_name_kana %>
                </td>
            </tr>
            <tr>
                <th>郵便番号</th>
                <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
                <th>住所</th>
                <td><%= f.text_field :address %></td>
            </tr>
            <tr>
                <th>電話番号</th>
                <td><%= f.text_field :phone_number %></td>
            </tr>
            <tr>
                <th>メールアドレス</th>
                <td><%= f.text_field :email %></td>
            </tr>
        </table>
        <%= f.submit '編集内容を保存する', class:"btn btn-primary col-xs-2" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user container">
    <!-- ユーザー情報表示用 -->
    <table class="user__info">
        <tr>
            <th>ユーザー情報</th>
            <td class="user__info--name"><%= @user.username %></td>
        </tr>
        <tr>
            <th>郵便番号</th>
            <td class="user__info--postal"><%= @user.postal_code %></td>
        </tr>
        <tr>
            <th>住所</th>
            <td class="user__info--address"><%= @user.address %></td>
        </tr>
        <tr>
            <th>電話番号</th>
            <td class="user__info--phone"><%= @user.phone_number %></td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td class="user__info--email"><%= @user.email %></td>
        </tr>
    </table><br />

    <!-- 出品物表示用 -->
    <div class="user__exhibition">
        <h2><strong>出品物</strong></h2>
        <% if @user.items.nil? %>
            出品物はありません。
        <% else %>
            <div class="row">
                <% @items.each do |itm| %>
                    <div class="user__exhibition--list col-md-4">
                        <div class="user__exhibition--name">
                            <div class="user__exhibition--item">
                                <%= link_to item_path(itm) do %>
                                  <%= itm.name %><br />
                                <% end %>
                                <p>出品設定額：<%= itm.listed_price %>円</p>
                                <!-- ブーストされている場合金額を表示 -->
                                <% if itm.listed_price_boost.nil?%>
                                <% else %>
                                    ※購入者によって<%= itm.listed_price %>円ブーストされました<br />
                                <% end %>
                                <%= itm.genre_id %><br />
                                <% if itm.selling_status == 0 %>
                                    販売中
                                <% elsif itm.selling_status == 1 %>
                                    <p>購入済み　以下住所に商品を発送してください</p>
                                    <p>購入者：<%= itm.ex_username %></p>
                                    <p>〒<%= itm.postal_code %></p>
                                    <p>住所：<%= itm.address %></p>
                                    <%= link_to "発送完了を通知する", item_finish_path( itm.id ), class: 'item-finish-btn btn btn-primary', method: :put %>
                                <% elsif itm.selling_status == 2 %>
                                    発送完了通知済
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>

    <!-- 購入履歴表示用 -->
    <h2 id="order__list"><strong>購入履歴</strong></h2>
    <% @orders.each do |ord| %>
        <div class="order__list--info col-md-4">
            <div class="order__list--name">
                <%= link_to item_path(ord.item.id) do %>
                    <%= ord.item_name %>
                <% end %>
            </div>
            <div class="order__list--price">
                ￥<%= ord.total_price %>
            </div>
            <div class="order__list--order_status">
                <% if ord.order_status == 0 %>
                    <div id="0 pre_shipping">注文受付中</div>
                <% elsif ord.order_status == 1 %>
                    <div id="1 shipping">商品発送中</div>
                <% else %>
                    <div id="2 finish_shipping">取引完了</div>
                <% end %>
            </div>
        </div>
    <% end %>
</div>


app/views/users/withdraw.html.erb
withdrawページ