config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  #ユーザー用ルーティング
  resources :users, only: [:show, :update, :edit, :destroy]
  # 退会確認ページ用
  get '/users/withdraw' => 'users#withdraw'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  # アバウト,トップページ用
  get '/homes/about' => 'homes#about'
  get '/homes/top' => 'homes#top'
  root to: 'homes#top'

  # 出品ページ用
  get '/items/exhibition' => 'items#exhibition'

  put '/items/finish/:id' => 'items#finish', as: 'item_finish'

  # 商品用ルーティング（コメント、お気に入り）
  put '/items/buy/:id' => 'items#buy', as: 'item_buy'

  put '/items/boost/:id' => 'items#boost', as: 'item_boost'

  resources :items, only: [:index, :show, :create, :edit, :destroy] do
    resource :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :item
	attachment :image
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include ApplicationHelper
    before_action :authenticate_user!

    def index
        # ログインユーザのカートアイテムを全部取得
        @orders = current_user.orders
    end

    def show
    end

    def create
        # orderテーブルの全てのカラム情報を取得
        # item = Item.find(params[:id])
        order = Order.new( order_item_params )
        # ユーザの関連付け
        order.user_id = current_user.id
        # 注文履歴の登録
        order.save
        # OrderDetailテーブルに購入商品の情報を追加する
        gets_purchasing_information( current_user.items ).each do | order_detail |
          # order_idの格納
          order_detail.order_id = order.id
          # OrderDetailテーブルに登録
          order_detail.save
        end
        # 購入情報入力画面へ遷移
        redirect_to item_path
    end

    def confirm
        @order = Order.new
      	@item = Item.find([:id])
    end

    private
    def order_item_params
        # 購入処理を進める商品の情報を取得
        params.require( :order ).permit( :postal_code, :ship_to, :consignee, :payment, :postage, :total_price )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
    def gets_purchasing_information( item )
        # 合計金額を格納する変数
        @total_price = 0
        objects = item.map do | item |
            # 空のOrderDetailオブジェクトを作成
            order_detail = OrderDetail.new
            # item_idを取得
            order_detail.item_id = item.item_id
            # 購入価格を算出・取得
            order_detail.purchased_price = item.item.listed_price
            # 各商品の購入金額の加算処理
            @total_price += order_detail.purchased_price
            # order_id以外が入力されたOrderDetailオブジェクトを返す
            order_detail
        end
        # OrderDetailオブジェクト群に変換された変数を返す
        return objects
    end
end

app/views/orders/confirm.html.erb
<div class="container">
  <h3><strong>購入情報確認</strong></h3>

  <table>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
    </tr>
    <tr>
      <td>
        <!--商品イメージ-->
        <%= attachment_image_tag @item, :image, size:'70x70', format: 'jpeg', fallback: 'no_image.jpg', size:'70x70' %>
        <!--商品名-->
        <%= order_detail.item.name %>
      </td>
      <td>
        <!-- 単価（税込）-->
        <%= number_separation( order_detail.purchased_price / order_detail.amount ) %>
      </td>
      <td>
        <!-- 数量-->
        <%= order_detail.amount %>
      </td>
      <td>
        <!-- 小計-->
        <%= number_separation( order_detail.purchased_price ) %>
      </td>
    </tr>
    <% end %>
  </table>

  <%= form_for( @order, url: orders_path ) do | f | %>
  <!-- 郵便番号-->
  <%= f.hidden_field :postal_code, readonly:true %>
  <!-- 配送先住所-->
  <%= f.hidden_field :ship_to, readonly:true %>
  <!-- 宛名-->
  <%= f.hidden_field :consignee, readonly:true %>
  <!-- 支払方法-->
  <%= f.hidden_field :payment, readonly:true %>
  <table>
    <tr>
      <td>配送料</td>
      <%= f.hidden_field :postage, value:@default_postage, readonly:true %>
      <td><%= @default_postage %></td>
    </tr>
    <tr>
      <td>商品合計</td>
      <td><%= number_separation( @total_price ) %></td>
    </tr>
    <tr>
      <td><b>請求金額</b></td>
      <% sum = @default_postage + @total_price %>
      <%= f.hidden_field :total_price, value:(sum), readonly:true %>
      <td><%= number_separation( sum ) %></td>
    </tr>
  </table>

  <h2>支払方法</h2>
  <%= @order.payment %>

  <h2>お届け先</h2>
  <%= join_address( @order.postal_code, @order.ship_to, @order.consignee ) %>

  <div style="display: block;">
    <%= f.submit '購入を確定する', class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <%= link_to '編集する', edit_user_path(current_user.id), class: "btn btn-primary" %>

    <table class="my-profile">
      <tr>
        <th>表示ネーム</th>
        <td>
          <!--名前の表示-->
          <%= current_user.username %>
        </td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= current_user.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= current_user.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= current_user.phone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= current_user.email %></td>
      </tr>
    </table><br>

    <strong>配送先を確認<%= link_to '一覧を見る', addresses_path, class: "btn btn-primary" %></strong><br>
    <strong>注文履歴一覧<%= link_to '一覧を見る', orders_path, class: "btn btn-primary" %></strong>

    <div class="order container">
        <table class="order__list">
          <tr>
            <th>オーダーリスト</th>
            <td>
              <!--名前の表示-->
              <%= current_user.username %>
            </td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= current_user.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= current_user.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= current_user.phone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= current_user.email %></td>
          </tr>
        </table><br>
    </div>
</div>
