config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  #ユーザー用ルーティング
  resources :users, only: [:show, :update, :edit, :destroy]
  # 退会確認ページ用
  get '/users/withdraw' => 'users#withdraw'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  # アバウト,トップページ用
  get '/homes/about' => 'homes#about'
  get '/homes/top' => 'homes#top'
  root to: 'homes#top'

  # 出品ページ用
  get '/items/exhibition' => 'items#exhibition'

  put '/items/finish/:id' => 'items#finish', as: 'item_finish'

  # 商品用ルーティング（コメント、お気に入り）
  put '/items/buy/:id' => 'items#buy', as: 'item_buy'

  put '/items/boost/:id' => 'items#boost', as: 'item_boost'

  resources :items, only: [:index, :show, :create, :edit, :destroy] do
    resource :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
    validates :introduction, presence: true, length: { maximum: 5000 }
    validates :name, presence: true, length: { maximum: 20 }
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
    attachment :image
    attachment :image2
    attachment :image3
    has_many :item_comments, dependent: :destroy
    has_one :order

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	include ApplicationHelper

	def index
		@items = Item.all
		# ransackを用いた検索機能
		@search = Item.search(params[:q])
		@items = @search.result(distinct: true)
		respond_to do |format|
			format.html
			format.json { render json: @items }
		end
	end

	def show
		# 閲覧する商品情報を取得
		@item = Item.find(params[:id])
		# コメント機能
		@item_comment = ItemComment.new
	    @item_comments = @item.item_comments
	    # サインインしている場合オーダーを作成する
   		if user_signed_in? then
			@order = Order.new
		end
	end

	def exhibition
		@item = Item.new
	end

	def create
	    @item = Item.new(item_params)
	    @item.user_id = current_user.id
	    @item.address = current_user.address
	    @item.email = current_user.email
	    @item.postal_code = current_user.postal_code
	    # アイテムに出品者名を登録する
	    @item.ex_username = join_ex_username( current_user.last_name, current_user.first_name )
	    if @item.save
			flash[:notice] = "商品の出品が完了しました。"
	    	redirect_to @item
	    else
			flash[:notice] = "商品の出品に失敗しました。"
	    	@items = Item.all
			redirect_to items_path
	    end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def boost
		@item = Item.find(params[:id])
	    @item.update( item_params )
	    flash[:notice] = "ブースト額を登録しました。"
		redirect_to action: 'show'
	end

	def buy
		@item = Item.find(params[:id])
		@user = User.find(current_user.id)
		exuser = @item.user
		# orderテーブルに格納する準備
		orders = Order.new
		flash[:notice] = "商品の購入処理が完了しました。"
		# orderテーブルに購入情報を格納
		orders.item_id = @item.id
		orders.item_name = @item.name
		orders.image_id = @item.image_id
		orders.user_id = current_user.id
		orders.postal_code = @user.postal_code
		orders.ship_to = @user.address
		orders.consignee = join_ex_username( @user.last_name, @user.first_name )
		# 処理時にブーストした金額と送料（一律800円）を上乗せする
		orders.total_price = @item.listed_price + @item.listed_price_boost + 800
		# 情報を保存
		orders.save
		if orders.save
		    # ContactMailer.send_when_item_bought( @user, @item ).deliver
			@item.selling_status = 1
			@item.ex_username = current_user.username
			@item.address = current_user.address
			@item.email = current_user.email
			@item.postal_code = current_user.postal_code
			@item.save
	    	redirect_to items_url
	    end
    end

    def finish
    	item = Item.find(params[:id])
    	item.selling_status = 2
    	if item.save
		  	flash[:notice] = "商品の出荷を通知しました。"
		    redirect_to items_url
		end
	end

	def destroy
	    @item = Item.find(params[:id])
	    @item.destroy
	  	flash[:notice] = "商品を取り下げました。"
	    redirect_to items_url
	end

    private
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :listed_price, :listed_price_boost, :image, :image2, :image3)
    end

    def correct_user
      item = Item.find(params[:id])
      if item.user.id != current_user.id
         redirect_to items_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="row">
	<%= form_for( @item, url:item_path( @item ) ) do | itm | %>
		<div class="col-lg-5">
			<div class="field">
		      	<%= itm.label :name, 'この商品の名前は？' %><br />
				<%= itm.text_field :name, placeholder: "入力してください" %><br />
			</div>
			<div class="field">
		      	<%= itm.label :introduction, 'この商品にまつわるおもいでは？' %><br />
				<%= itm.text_area :introduction, size: "50x15", placeholder: "入力してください" %><br />
			</div>
			<div class="field">
				<!-- リスト形式でジャンルを選択 -->
		      	<%= itm.label :genre_id, 'おもいでのジャンルは？' %><br />
			    <%= itm.select :genre_id, Genre.all.map{|genre|[genre.name, genre.id]}.to_h , prompt:'--選択してください--' %><br />
			</div>
			<div class="field">
		      	<%= itm.label :listed_price, 'この商品の値段は？' %><br />
				<%= itm.number_field :listed_price, min:0 %><br />
			</div>
		</div>

	<div class="col-lg-7">
      	<%= itm.label :image, 'この商品の画像は？' %><br />
	    <%= attachment_image_tag @item, :image, fallback: 'no_image.jpg', size:'350x350' %>
	    <%= itm.attachment_field :image, placeholder: "商品画像を変更" %>
	</div>

	<div class="field">
	   	<%= itm.submit "これで登録する", class: "btn btn-primary" %><br />
	   	<%= link_to '商品を取り下げ', item_path(@item.id), class: 'btn btn-danger', method: :delete %>
	</div>
	<% end %>
</div>

app/views/items/exhibition.html.erb
<div class="row">
	<%= form_for( @item, url:items_path ) do | itm | %>
		<div class="col-lg-7">
			<div class="field">
			   	<%= itm.label :name, 'この商品の名前は？' %><br />
				<%= itm.text_field :name, placeholder: "入力してください" %><br />
			</div>
			<div class="field">
			   	<%= itm.label :introduction, 'この商品にまつわるおもいでは？' %><br />
				<%= itm.text_area :introduction, size: "50x15", placeholder: "入力してください" %><br />
			</div>
			<div class="field">
				<!-- リスト形式でジャンルを選択 -->
			   	<%= itm.label :genre_id, 'おもいでのジャンルは？' %><br />
			    <%= itm.select :genre_id, Genre.all.map{|genre|[genre.name, genre.id]}.to_h , prompt:'--選択してください--' %><br />
			</div>
			<div class="field">
			   	<%= itm.label :listed_price, 'この商品の値段は？' %><br />
				<%= itm.number_field :listed_price, min:0, placeholder: "〇〇円で入力" %><br />
			</div>
			<div class="field">
			   	<%= itm.submit "商品を出品する", class: "btn btn-primary" %><br />
			</div>
		</div>
		<div class="col-lg-5">
	      	<%= itm.label :image, 'この商品の画像は？' %><br />
		    <%= itm.attachment_field :image, placeholder: "商品画像を変更" %>
		    <%= itm.attachment_field :image2, placeholder: "商品画像を変更" %>
		    <%= itm.attachment_field :image3, placeholder: "商品画像を変更" %>
		</div>
	<% end %>
</div>

app/views/items/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1>アイテム一覧ページ</h1><br />
	</div>
	<!-- 取得したitemsをeach文で表示していく -->
    <%= search_form_for @search do |sch| %>
        <%= sch.search_field :name_cont, placeholder:"キーワードで探す" %>
        <%= sch.submit "検索" %>
    <% end %>
    <% @items.all.each do | itm | %>
		<div class="col-lg-4">
			<div class="item-index-image">
				<%= link_to item_path( itm ) do %>
			        <%= attachment_image_tag itm, :image, size:'250x250', class: 'item-index-image' %>
			    <% end %>
			</div>

      		<%= link_to itm.name, item_path( itm ) %><br />
		    <%= itm.listed_price %><br />
			<%= link_to item_path( itm ) do %>
			    <%= itm.genre_id %>
			<% end %>
		    <% if itm.selling_status == 0 %>
		    	取引中
	    	<% else %>
			    取引終了
			<% end %>
		    <%= itm.item_comments.count %>コメント

		    <% if itm.favorited_by?(current_user) %>
	        	<%= link_to item_favorites_path(itm, redirect_id: 0), method: :delete do %>
	    	      	<span class="glyphicon glyphicon-heart"><%= itm.favorites.count%></span>
		        <% end %>
		    <% else %>
	            <%= link_to item_favorites_path(itm, redirect_id: 0), method: :post do %>
	            	<span class="glyphicon glyphicon-heart-empty"><%= itm.favorites.count %></span>
	            <% end %>
	        <% end %>
		</div>
	<% end %>
</div>

app/views/items/show.html.erb
<div class="itemshow row">
    <div class="itemshow__data--image col-xs-12">
        <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: 'no_image.jpg' %>
        <% if @item.image2 == nil? %>
        <% else %>
            <%= attachment_image_tag @item, :image2, format: 'jpeg' %>
        <% end %>
        <% if @item.image3 == nil? %>
        <% else %>
            <%= attachment_image_tag @item, :image3, format: 'jpeg' %>
        <% end %>
    </div>
    <div class="itemshow__data col-xs-7">
        <div class="itemshow__data--name col-xs-7">
            <h2><strong><%= @item.name %></strong></h2><br />
            <!-- アイテムの説明 -->
            <div class="itemshow__data--introduction">
                <p><%= @item.introduction %></p><br />
            </div>
        </div>
      	<!-- 桁数が多い場合カンマ区切りにするヘルパーを使用 -->
        <div class="itemshow__data--price">
          	出品者希望額 <%= number_separation ( @item.listed_price )%>円
            <% if user_signed_in? then %>
                <% unless @item.user_id == current_user.id then %>
                    <%= form_for( @item, url:item_boost_path( @item ), html: {method: 'put'} ) do | itm | %>
                        <!-- 購入価格ブースト機能 -->
                        <%= itm.number_field :listed_price_boost, placeholder: "＋金額をブーストする" ,step:100 ,min:0 %>
                        <%= itm.submit "ブースト金額を登録", class: "btn btn-primary" %><br />
                    <% end %>
                <% end %>
            <% else %>
            <% end %>
        </div>
        <div class="itemshow__data--fav">
      		<!-- お気に入り機能 -->
            <% if user_signed_in? then %>
                <% if @item.favorited_by?(current_user) %>
                    <%= link_to item_favorites_path(@item, redirect_id: 0), method: :delete do %>
                        <span class="glyphicon glyphicon-heart"><%= @item.favorites.count%></span>
                    <% end %>
                <% else %>
                    <%= link_to item_favorites_path(@item, redirect_id: 0), method: :post do %>
                        <span class="glyphicon glyphicon-heart-empty"><%= @item.favorites.count %></span>
                    <% end %>
                <% end %>
            <% end %>
        </div>

        <div class="itemshow__data--buy">
     		<!-- ログインせずに購入ボタンを推すとログインを促すウィンドウが表示される -->
            <% if user_signed_in? then %>
                <% unless @item.user_id == current_user.id then %>
                    <% if @item.selling_status = 0 then %>
                        <button id="modal-open-btn", class="btn btn-primary">商品を購入する</button>
                        <%= link_to "", item_buy_path( @item.id ), id: 'item-buy-btn', method: :put %>
                        <!-- モーダルウィンドウ用タグ -->
                        <div id="overlay">
                            <div id="modalWindow">
                                <div class="modal-message-box">
                                    <p>本当に購入しますか？</p>
                                </div>
                                <button id="modal-close-btn">キャンセル</button>
                                <button id="item-bought-btn">商品を購入する</button>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% else %>
          	    <%= link_to 'ユーザー登録して購入する', new_user_registration_path, class: "btn btn-primary" %>
            <% end %>
        </div>

        <div class="itemshow__data--edit">
            <!-- 自分が出品したアイテムの場合は編集用ボタンを表示 -->
            <% if user_signed_in? then %>
  	            <% if @item.user == current_user %>
   	                <%= link_to '編集する', edit_item_path( @item ), class: "btn btn-primary" %>
                <% end %>
            <% end %>
        </div>
    </div>

    <div class="itemshow__comment row">
    	<h2>コメント：<%= @item_comments.count %></h2>
        <table class="itemshow__comment--list">
        <!-- コメント一覧表示 -->
            <% @item_comments.each do |itm_co| %>
    	        <tr>
    	            <td><div class="field">
    	               <%= link_to item_path(itm_co.user), class: "user_#{itm_co.user.id}" do %>
    	                   <%= itm_co.user.username %>｜
    	               <% end %>
               	    </div></td>
    	            <td><div class="field">
    	          	    <%= itm_co.comment %>
    	            </div></td>
    	            <!-- 投稿者とログインユーザーが同じ場合削除ボタン表示 -->
    	            <% unless current_user != itm_co.user %>
    	                <td><div class="field">
    	            	    ｜<%= link_to 'Destroy', item_item_comments_path(itm_co.id), class: 'btn-sm btn-danger', method: :delete %>
    	                </div></td>
    	            <% end %>
    	        </tr>
            <% end %>
        </table>
    </div>

    <div class="itemshow__comment--submit row">
        <%= form_for [@item, @item_comment] do |f| %>
            <%= f.text_area :comment, size: "90x5", placeholder: "コメントを入力する" %>
            <%= f.submit '送信' ,class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

<div class="itemshow__back row">
	<%= link_to items_path do %>
		商品一覧に戻る
	<% end %>
</div>