config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  #ユーザー用ルーティング
  resources :users, only: [:show, :update, :edit, :destroy]
  # 退会確認ページ用
  get '/users/withdraw' => 'users#withdraw'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  # アバウト,トップページ用
  get '/homes/about' => 'homes#about'
  get '/homes/top' => 'homes#top'
  root to: 'homes#top'

  # 出品ページ用
  get '/items/exhibition' => 'items#exhibition'

  put '/items/finish/:id' => 'items#finish', as: 'item_finish'

  # 商品用ルーティング（コメント、お気に入り）
  put '/items/buy/:id' => 'items#buy', as: 'item_buy'

  put '/items/boost/:id' => 'items#boost', as: 'item_boost'

  resources :items, only: [:index, :show, :create, :edit, :destroy] do
    resource :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>おもいで通販</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width,initial-scale=1.0">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- ログイン中の場合のみトップバーを表示 -->
        <% if user_signed_in? %>
            <header class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <nav class="nav navbar-nav navbar-left">
                      <%= link_to root_path do %>
                      <%= image_tag 'omoide_logo.png', size:'200x45' %>
                      <% end %>
                    </nav>
                    <ul>
                        <div class="nav navbar-nav navbar-right normal-menu">
                            <li>
                                ログインユーザ：<%= current_user.username%> さん<br>
                                <% if flash.any? then %>
                                    <% flash.each do |key, value| %>
                                        <%= value %>
                                    <% end %>
                                    <% end %>
                            </li>
                            <li><%= link_to "出品する", items_exhibition_path %></li>
                            <li><%= link_to "商品を探す", items_path %></li>
                            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                        </div>
                        <!-- レスポンシブ対応　ハンバーガーアイコン -->
                        <div id="sp-menu">
                            <ul>
                                <li><%= link_to "出品する", items_exhibition_path %></li>
                                <li><%= link_to "商品を探す", items_path %></li>
                                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                            </ul>
                        </div>
                        <div id="hm-icon">
                            <a class="menu-trigger" href="#">
                                <span></span>
                                <span></span>
                                <span></span>
                            </a>
                        </div>
                    </ul>
                </div>
            </header>
        <% else %>
        <% end %>
    </head>

    <body>
        <div class="container">
            <%= yield %>
        </div>
    </body>

    <footer>
        © 2020 Seiya Ito inc.<br />
        ポートフォリオ用サイトです。実際の取引はできません。
    </footer>
</html>